### PR TITLE
feat: ja translate develop/index

### PR DESCRIPTION
**Pull request by riywo**

### CODE REVIEW

**Comment by riywo** [comment]
Failed by https://github.com/momentohq/client-sdk-javascript/commit/34836c9c81e100c5ae806e767244642ce005d3a2

**Comment by riywo** [comment]
CI failed by https://github.com/momentohq/client-sdk-javascript/commit/cdc7776d1b32e425f10cc0cc0cc8a79efad095e8

**Comment by riywo** [comment]
@poppoerika ^^

**Comment by poppoerika** [comment]
@riywo 
Closing this PR since it was addressed in https://github.com/momentohq/public-dev-docs/pull/274

**Pull request closed without merging**
