### PR TITLE
chore: remove mvi

### PR DESCRIPTION
**Pull request by rishtigupta**
## PR Description:
- Remove MVI related docs

## Issue
https://github.com/momentohq/dev-eco-issue-tracker/issues/788

### CODE REVIEW

**Comment by cprice404** [comment]
Thanks!

Did you intend to include the change to the leaderboard graphic?

Also, before we merge this, I wanna check and see if we should add any redirects to prevent broken links.

**Review by cprice404 — COMMENTED** [review]
@rishtigupta :ty: , can we add redirects from the deleted pages to the docs home page before we merge?

**Comment by rishtigupta** [comment]
> Thanks!
> 
> Did you intend to include the change to the leaderboard graphic?
> 
> Also, before we merge this, I wanna check and see if we should add any redirects to prevent broken links.

Yes, the leaderboard color change was intended. Since the cards were arranged with alternating colors, needed to change the leaderboard color to match that pattern:

Current:
Screenshot 2024-04-17 at 12 59 17 PM


Updated:
Screenshot 2024-04-17 at 12 57 57 PM

**Comment by cprice404** [comment]
We were holding off on this because we weren't sure the redirects were working.

I pulled down this branch locally and launched the server, and noted that *none* of the redirects seem to work locally (specifically was testing the /develop/sdk redirects), even though they work on the live website.

So I think we shouldn't block this PR on the redirects, we should just test them once it deploys and update if necessary.

**Review by cprice404 — APPROVED** [review]

**Pull request merged**
