### PR TITLE
Fix ja/intro.md by removing unnecessary tags and more

### PR DESCRIPTION
**Pull request by riywo**
The page contains unnecessary `<br/>` tags and some minor misses.

This commit removes `<br/>` tags and the link for guides.

### CODE REVIEW

**Comment by riywo** [comment]
@poppoerika Minor fixes on the existing JP page.

**Review by poppoerika — APPROVED** [review]
Thank you for doing this!
I think we need to add some styling to adjust where Japanese words are cut off.
At least for laptop and mobile views. Will create a ticket for that.

**Comment by riywo** [comment]
It's not easy to set proper word breaks for everywhere in Japanese i.e. a non-whitespace language. I think most of technical document sites just rely on how browser treats and sometime it looks weird, of course, but I think it's OK for technical documents. It's everywhere on WWW, TBH.

**Comment by poppoerika** [comment]
@riywo Thank you for the insight! Yeah, sounds good.
I think it's okay for now.

**Comment by riywo** [comment]
@poppoerika Awesome! Could you merge as I don't have such permission?

**Pull request merged**
